use_frameworks!

target 'Align_Example' do
  platform :ios, '10.0'
  pod 'Align', :path => '../'

  target 'Align_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
